version: '3.1'

services:

  revproxyinjector:
    container_name: revproxyinjector
    build:
      context: .
      dockerfile: Dockerfile.integration.test
    command: ["-c", "./main -host http://web"]

  web:
    image: php:7.2-apache
    volumes:
      - ./__web__:/var/www/html